const DEFAULT_EXTENSIONS = {
  images: {
    label: "Imagens",
    extensions: [
      ".jpg",
      ".jpeg",
      ".png",
      ".gif",
      ".bmp",
      ".svg",
      ".webp",
      ".ico",
    ],
  },
  documents: {
    label: "Documentos",
    extensions: [
      ".pdf",
      ".doc",
      ".docx",
      ".xls",
      ".xlsx",
      ".ppt",
      ".pptx",
      ".txt",
      ".rtf",
      ".odt",
      ".ods",
      ".odp",
    ],
  },
  code: {
    label: "Código",
    extensions: [
      ".js",
      ".ts",
      ".jsx",
      ".tsx",
      ".py",
      ".java",
      ".c",
      ".cpp",
      ".cs",
      ".rb",
      ".go",
      ".rs",
      ".php",
      ".html",
      ".css",
      ".scss",
      ".json",
      ".xml",
      ".yaml",
      ".yml",
      ".toml",
    ],
  },
  videos: {
    label: "Vídeos",
    extensions: [
      ".mp4",
      ".avi",
      ".mov",
      ".wmv",
      ".flv",
      ".mkv",
      ".webm",
      ".m4v",
    ],
  },
  audio: {
    label: "Áudio",
    extensions: [".mp3", ".wav", ".flac", ".aac", ".ogg", ".wma", ".m4a"],
  },
  compressed: {
    label: "Compactados",
    extensions: [".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz", ".iso"],
  },
  executables: {
    label: "Executáveis",
    extensions: [
      ".exe",
      ".msi",
      ".apk",
      ".dmg",
      ".deb",
      ".rpm",
      ".sh",
      ".bat",
      ".cmd",
    ],
  },
  data: {
    label: "Dados",
    extensions: [".csv", ".tsv", ".sql", ".db", ".sqlite", ".mdb", ".parquet"],
  },
  fonts: {
    label: "Fontes",
    extensions: [".ttf", ".otf", ".woff", ".woff2", ".eot"],
  },
  design: {
    label: "Design",
    extensions: [".ai", ".eps", ".psd", ".xd", ".sketch", ".fig"],
  },
};

export default DEFAULT_EXTENSIONS;
